#%RAML 1.0 DataType
type: object
properties:
  events:
    type: array
    items:
      type: object
      properties:
        id: integer
        name: string
        description?: string
        format: integer
        courseid: integer
        groupid: integer
        userid: integer
        repeatid?: integer | nil
        modulename?: string
        instance: integer
        eventtype: string
        timestart: integer
        timeduration: integer
        visible: integer
        uuid?: string
        sequence: integer
        timemodified: integer
        subscriptionid?: integer | nil
  warnings?:
    type: array
    items:
      type: object
      properties:
        item?: string
        itemid?: integer
        warningcode: string
        message: string
