#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    id: integer
    name: string
    idnumber?: string
    description: string
    descriptionformat: integer
    parent: integer
    sortorder: integer
    coursecount: integer
    visible?: integer
    visibleold?: integer
    timemodified?: integer
    depth: integer
    path: string
    theme?: string
