#%RAML 1.0
title: Moodle
version: v1
baseUri: https://nexturn.moodlecloud.com/webservice/rest/server.php
protocols: [ HTTPS ]
mediaType:
  - application/json
  - application/x-www-form-urlencoded
description: Moodle LMS (Learning Management System) is a widely used open-source platform designed for managing, delivering, and measuring online learning and training. It offers a fully customizable online learning environment suitable for various educational settings, from K–12 classrooms to large universities and enterprises.

traits:
  errorResponse: !include /traits/errorResponse-trait.raml
  commonHeaders: !include /traits/commonHeaders-trait.raml
types:
  commonResponse: !include /datatypes/common/common-dataType.raml
  coreCourseGetCourses: !include /datatypes/courses/coreCourseGetCourse-dataType.raml
  createCourse: !include /datatypes/courses/createCourse-dataType.raml
  getCourseByField: !include /datatypes/courses/getCoursesByField-dataType.raml
  updateDeleteCourse: !include /datatypes/courses/updateDeleteCourse-dataType.raml
  getGrades: !include /datatypes/grades/getGrades-dataType.raml
  getCourseGrades: !include /datatypes/grades/getCourseGrades-dataType.raml
  createCalendar: !include /datatypes/calendar/createCalendar-dataType.raml
  getCalendar: !include /datatypes/calendar/getCalendar-dataType.raml
  getCalendarById: !include /datatypes/calendar/getCalendarById-dataType.raml
  getCalendarTimesort: !include /datatypes/calendar/getCalendarTimesort-dataType.raml
  getAssignments: !include /datatypes/assignments/getAssignments-dataType.raml
  getAssignmentSubmission: !include /datatypes/assignments/getAssignmentSubmission-dataType.raml
  getAssignmentGrades: !include /datatypes/assignments/getAssignmentGrades-dataType.raml
  coreUserGetUsersResponse: !include /datatypes/user/getUsers-dataType.raml
  coreUserGetUsersByFieldResponse: !include /datatypes/user/getUsersById-dataType.raml
  coreUserCreateUsersResponse: !include /datatypes/user/createUser-dataType.raml
  coreUserUpdateUsersResponse: !include /datatypes/user/updateUser-dataType.raml
  coreGroupCreateGroupingsResponse: !include /datatypes/groups/createGroupings-dataType.raml
  coreGroupGetGroupMembersResponse: !include /datatypes/groups/getGroupMembers-datatype.raml
  coreCourseGetCategories: !include /datatypes/courseCategory/getCategories-dataType.raml
  coreCourseCreateCategories: !include /datatypes/courseCategory/createCategories-dataType.raml
  coreGroupGetGroups: !include /datatypes/groups/getGroups-dataType.raml
  coreGroupCreateGroups: !include /datatypes/groups/createGroups-dataType.raml
  coreGroupGetCourseGroups: !include /datatypes/groups/getCourseGroups-dataType.raml
  coreGroupGetCourseGroupings: !include /datatypes/groups/getCourseGroupings-dataType.raml
  enrolManualEnrolUsers: !include /datatypes/enrollment/enrolManualEnrolUsers-dataType.raml
  enrolManualUnenrolUsers: !include /datatypes/enrollment/enrolManualUnenrolUsers-dataType.raml
  coreEnrolGetEnrolledUsers: !include /datatypes/enrollment/getEnrolledUsers-dataType.raml
  coreEnrolGetUsersCoursesResponse: !include /datatypes/enrollment/getUsersCourses-datatype.raml
  coreEnrolUnenrolUserEnrolment: !include /datatypes/enrollment/unenrolUserEnrolment-dataType.raml
  Cohort: !include /datatypes/cohort/cohort-dataType.raml
  AddCohortMemberResponse: !include /datatypes/cohort/addCohortMember-dataType.raml
  DeleteCohortResponse: !include /datatypes/cohort/deleteCohort-dataType.raml
  DeleteCohortMemberResponse: !include /datatypes/cohort/deleteCohortMember-dataType.raml
  GetCohortMembers: !include /datatypes/cohort/getCohortMembers-dataType.raml
  CohortItem: !include /datatypes/cohort/getCohorts-dataType.raml
  CohortTypes: !include /datatypes/cohort/updateCohorts-dataType.raml

/core_course_get_courses:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course - Get Courses
    description: Get list of courses from Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_get_courses
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
    responses:
      200:
        body:
          application/json:
            type: coreCourseGetCourses
            example: !include /examples/courses/coreCourseGetCourse-example.json

/core_course_create_courses:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course - Create Courses
    description: Create Courses
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_create_courses
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courses[0][fullname]:
            type: string
            required: true
            example: Sample Full Course Name
          courses[0][shortname]:
            type: string
            required: true
          courses[0][categoryid]:
            type: integer
            required: true
          courses[0][idnumber]:
            type: string
            required: true
          courses[0][summary]:
            type: string
            required: false
          courses[0][summaryformat]?: integer
          courses[0][format]?: string
          courses[0][showgrades]?: integer
          courses[0][newsitems]?: integer
          courses[0][startdate]?: integer
          courses[0][enddate]?: integer
          courses[0][numsections]?: integer
          courses[0][maxbytes]?: integer
          courses[0][showreports]?: integer
          courses[0][visible]?: integer
          courses[0][hiddensections]?: integer
          courses[0][groupmode]?: integer
          courses[0][groupmodeforce]?: integer
          courses[0][defaultgroupingid]?: integer
          courses[0][enablecompletion]?: integer
          courses[0][completionnotify]?: integer
          courses[0][lang]?: string
          courses[0][forcetheme]?: string
          courses[0][courseformatoptions][0][name]?: string
          courses[0][courseformatoptions][0][value]?: integer
          courses[0][customfields][0][shortname]?: string
          courses[0][customfields][0][value]?: string
    responses:
      200:
        body:
          application/json:
            type: createCourse
            example: !include /examples/courses/createCourse-example.json

/core_course_get_courses_by_field:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course - Get Courses by Field
    description: Get Courses by Field
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_get_courses_by_field
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          field?: any
    responses:
      200:
        body:
          application/json:
            type: getCourseByField
            example: !include /examples/courses/getCoursesByField-example.json
/core_course_update_courses:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course - Update Courses
    description: Update Courses
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_update_courses
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courses[0][id]: integer
          courses[0][fullname]:
            type: string
            required: true
            example: Sample Full Course Name
          courses[0][shortname]:
            type: string
            required: true
          courses[0][categoryid]:
            type: integer
            required: true
          courses[0][idnumber]:
            type: string
            required: true
          courses[0][summary]:
            type: string
            required: false
          courses[0][summaryformat]?: integer
          courses[0][format]?: string
          courses[0][showgrades]?: integer
          courses[0][newsitems]?: integer
          courses[0][startdate]?: integer
          courses[0][enddate]?: integer
          courses[0][numsections]?: integer
          courses[0][maxbytes]?: integer
          courses[0][showreports]?: integer
          courses[0][visible]?: integer
          courses[0][hiddensections]?: integer
          courses[0][groupmode]?: integer
          courses[0][groupmodeforce]?: integer
          courses[0][defaultgroupingid]?: integer
          courses[0][enablecompletion]?: integer
          courses[0][completionnotify]?: integer
          courses[0][lang]?: string
          courses[0][forcetheme]?: string
          courses[0][courseformatoptions][0][name]?: string
          courses[0][courseformatoptions][0][value]?: integer
          courses[0][customfields][0][shortname]?: string
          courses[0][customfields][0][value]?: string
    responses:
      200:
        body:
          application/json:
            type: updateDeleteCourse
            example: !include /examples/courses/updateDeleteCourse-example.json
/core_course_delete_courses:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course - Delete Courses
    description: Delete Courses
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_delete_courses
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courseids[0]: integer
    responses:
      200:
        body:
          application/json:
            type: updateDeleteCourse
            example: !include /examples/courses/updateDeleteCourse-example.json
/core_role_assign_roles:
  post:
    is: [commonHeaders,errorResponse]
    displayName: User Roles - Assign Roles
    description: Assign Roles
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_role_assign_roles
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          assignments[0][roleid]: integer
          assignments[0][userid]: integer
          assignments[0][contextid]?: integer
          assignments[0][contextlevel]?: string
          assignments[0][instanceid]?: integer
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_role_unassign_roles:
  post:
    is: [commonHeaders,errorResponse]
    displayName:  User Roles - Unassign Roles
    description: Unassign Roles
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_role_unassign_roles
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          unassignments[0][roleid]: integer
          unassignments[0][userid]: integer
          unassignments[0][contextid]?: integer
          unassignments[0][contextlevel]?: string
          unassignments[0][instanceid]?: integer
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/gradereport_user_get_grade_items:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Grade Report - Get Grade Items
    description: Get Grade Items
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: gradereport_user_get_grade_items
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courseid: integer
          userid?: integer
          groupid?: integer
          
    responses:
      200:
        body:
          application/json:
            type: getGrades
            example: !include /examples/grades/getGrades-example.json

/gradereport_overview_get_course_grades:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Grade Report - Get Course Grades
    description: Get Course Grades
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: gradereport_overview_get_course_grades
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          userid: integer       
    responses:
      200:
        body:
          application/json:
            type: getCourseGrades
            example: !include /examples/grades/getCourseGrades-example.json

/core_calendar_create_calendar_events:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Calendar - Create Calendar Events
    description: Create Calendar Events
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_calendar_create_calendar_events
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          events[0][name]: string
          events[0][description]: string
          events[0][format]: integer
          events[0][courseid]: integer
          events[0][groupid]: integer
          events[0][repeats]?: integer
          events[0][eventtype]: string
          events[0][timestart]?: integer
          events[0][timeduration]?: integer
          events[0][visible]?: integer
          events[0][sequence]?: integer
    responses:
      200:
        body:
          application/json:
            type: createCalendar
            example: !include /examples/calendar/createCalendar-example.json
/core_calendar_get_calendar_events:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Calendar - Get Calendar Events
    description: Get Calendar Events
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_calendar_get_calendar_events
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          events[0][courseid]?: integer
          events[0][groupid]?: integer
          events[0][eventids]?: integer
          events[0][categoryids]?: integer
    responses:
      200:
        body:
          application/json:
            type: getCalendar
            example: !include /examples/calendar/getCalendar-example.json
 
/core_calendar_delete_calendar_events:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Calendar - Delete Calendar Events
    description: Delete Calendar Events
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_calendar_delete_calendar_events
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          events[0][eventid]: integer
          events[0][repeat]: integer
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json

/core_calendar_get_calendar_event_by_id:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Calendar - Get Calendar Event by Id
    description: Get Calendar Event by Id
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_calendar_get_calendar_event_by_id
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          eventid: integer
    responses:
      200:
        body:
          application/json:
            type: getCalendarById
            example: !include /examples/calendar/getCalendarById-example.json

/core_calendar_get_action_events_by_timesort:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Calendar - Get Calendar events for students
    description: Get Calendar events for students
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_calendar_get_action_events_by_timesort
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          timesortfrom: 
            type: integer
            required: false
            default: 0
          timesortto:
            type: integer
            required: false
            default: null
          aftereventid:
            type: integer
            required: false
            default: 0
          limitnum:
            type: integer
            required: false
            default: 20
          limittononsuspendedevents:
            type: integer
            required: false
          userid:
            type: integer
            required: false
          searchvalue:
            type: string
            required: false
            default: null
    responses:
      200:
        body:
          application/json:
            type: getCalendarTimesort
            example: !include /examples/calendar/getCalendarTimesort-example.json

/mod_assign_get_assignments:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Assignments - Get all the course assignments
    description: Get all the course assignments
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: mod_assign_get_assignments
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courseids[0]: integer
    responses:
      200:
        body:
          application/json:
            type: getAssignments
            example: !include /examples/assignments/getAssignments-example.json

/mod_assign_get_submission_status:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Assignments - Get assignment submissions
    description: Get assignment submissions
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: mod_assign_get_submission_status
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          assignid: integer
          userid?: integer
          groupid?: integer
    responses:
      200:
        body:
          application/json:
            type: getAssignmentSubmission
            example: !include /examples/assignments/getAssignmentSubmission-examlple.json
/mod_assign_get_grades:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Assignments - Get assignment grades
    description: Get assignment grades
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: mod_assign_get_grades
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          assignmentids[0]: integer
          
    responses:
      200:
        body:
          application/json:
            type: getAssignmentGrades
            example: !include /examples/assignments/getAssignmentGrades-example.json
/core_user_get_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: User - Get Users
    description: Search for users matching criteria
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_user_get_users
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          criteria[0][key]:
            description: Search criteria key (e.g. username, email)
            type: string
            required: true
            example: firstname
          criteria[0][value]:
            description: Search criteria value
            type: string
            required: true
            example: Swayam
          # Add additional criteria as needed
    responses:
      200:
        body:
          application/json:
            type: coreUserGetUsersResponse
            example: !include /examples/user/getUsers-example.json
/core_user_get_users_by_field:
  post:
    is: [commonHeaders,errorResponse]
    displayName: User - Get Users by Id
    description: Retrieve users' information for a specified unique field
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_user_get_users_by_field
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          field:
            description: Search field (id, idnumber, username, email)
            type: string
            required: true
            example: id
          values[0]:
            description: Value to match for the search field
            type: integer
            required: true
            example: 14
    responses:
      200:
        body:
          application/json:
            type: coreUserGetUsersByFieldResponse
            example: !include /examples/user/getUsersById-example.json
/core_user_create_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: User - Create users
    description: Create new users in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_user_create_users
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          users[0][createpassword]:
            description: True if password should be created and mailed to user
            type: integer
            example: 0
          users[0][username]:
            description: Username (must follow Moodle policy)
            type: string
            example: swayam2002
          users[0][auth]:
            description: Authentication plugin (default manual)
            type: string
            example: manual
          users[0][password]:
            description: User password (plain text)
            type: string
            example: Test@1234
          users[0][firstname]:
            type: string
            example: Swayam
          users[0][lastname]:
            type: string
            example: Prusty
          users[0][email]:
            type: string
            example: swayam@example.com
          users[0][city]:
            type: string
            example: Bhubaneswar
          users[0][country]:
            type: string
            example: IN
          users[0][idnumber]:
            type: string
            example: STU12345
          users[0][customfields][0][type]:
            type: string
            example: moodle_custom_field
          users[0][customfields][0][value]:
            type: string
            example: Custom Value
          users[0][preferences][0][type]:
            type: string
            example: maildigest
          users[0][preferences][0][value]:
            type: string
            example: preferencevalue1
    responses:
      200:
        body:
          application/json:
            type: coreUserCreateUsersResponse
            example: !include /examples/user/createUser-example.json
/core_user_update_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: User - Update Users
    description: Update existing users in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_user_update_users
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          users[0][id]:
            description: User ID to be updated
            type: integer
            required: true
            example: 21
          users[0][firstname]:
            type: string
            example: Swayam Updated
          users[0][lastname]:
            type: string
            example: Prusty
          users[0][email]:
            type: string
            example: swayam.updated@example.com
          users[0][suspended]:
            type: integer
            example: 0
          users[0][customfields][0][type]:
            type: string
            example: moodle_custom_field
          users[0][customfields][0][value]:
            type: string
            example: Updated Value
          users[0][preferences][0][type]:
            type: string
            example: maildigest
          users[0][preferences][0][value]:
            type: string
            example: UpdatedPreferenceValue
    responses:
      200:
        body:
          application/json:
            type: coreUserUpdateUsersResponse
            example: !include /examples/user/updateUser-example.json
/core_user_delete_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: User - Delete Users
    description: Delete users from Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_user_delete_users
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          userids[0]:
            description: User ID to delete
            type: integer
            required: true
            example: 21
          
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_add_group_members:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Add Group Members
    description: Add users as members to groups in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_add_group_members
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          members[0][groupid]:
            description: Group ID
            type: integer
            required: true
            example: 5
          members[0][userid]:
            description: User ID
            type: integer
            required: true
            example: 21
          
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_delete_group_members:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Delete Group Members
    description: Delete users from groups in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_delete_group_members
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          members[0][groupid]:
            description: Group ID
            type: integer
            required: true
            example: 5
          members[0][userid]:
            description: User ID
            type: integer
            required: true
            example: 21
          
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_assign_grouping:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Assign Groupings
    description: Assign groups to groupings in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_assign_grouping
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          assignments[0][groupingid]:
            description: Grouping ID
            type: integer
            required: true
            example: 2
          assignments[0][groupid]:
            description: Group ID
            type: integer
            required: true
            example: 10
          
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_create_groupings:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Create Groupings
    description: Create new groupings in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_create_groupings
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          groupings[0][courseid]:
            description: Course ID
            type: integer
            required: true
            example: 15
          groupings[0][name]:
            description: Grouping name
            type: string
            required: true
            example: "Lab Grouping A"
          groupings[0][description]:
            description: Grouping description
            type: string
            required: true
            example: "This grouping is for lab sessions"
          groupings[0][descriptionformat]:
            description: Description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, 4 = MARKDOWN)
            type: integer
            required: true
            default: 1
            example: 1
          groupings[0][idnumber]:
            description: ID number
            type: string
            required: true
            example: "GRP-2025-01"
          groupings[0][customfields][0][shortname]:
            description: Custom field shortname
            type: string
            required: false
            example: "priority"
          groupings[0][customfields][0][value]:
            description: Custom field value
            type: string
            required: false
            example: "high"
    responses:
      200:
        body:
          application/json:
            type: coreGroupCreateGroupingsResponse
            example: !include /examples/groups/createGroupings-example.json
/core_group_get_group_members:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Get Group Members
    description: Get members of the specified groups in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_get_group_members
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          groupids[0]:
            description: Group ID
            type: integer
            required: true
            example: 5       
    responses:
      200:
        body:
          application/json:
            type: coreGroupGetGroupMembersResponse
            example: !include /examples/groups/getGroupMembers-example.json
/core_group_unassign_grouping:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Unassign Groupings
    description: Unassign groups from groupings in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_unassign_grouping
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          unassignments[0][groupingid]:
            description: Grouping record ID
            type: integer
            required: true
            example: 2
          unassignments[0][groupid]:
            description: Group record ID
            type: integer
            required: true
            example: 5
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_delete_groupings:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Delete Groupings
    description: Delete all specified groupings in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token for authentication
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_delete_groupings
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          groupingids[0]:
            description: Grouping ID
            type: integer
            required: true
            example: 3   
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json

/core_course_get_categories:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course Category - Get Categories
    description: Get list of course categories from Moodle with optional filtering criteria.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_get_categories
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          criteria[0][key]:
            description: Key for filter (id, ids, name, parent, idnumber, visible, theme)
            type: string
            example: name
          criteria[0][value]:
            description: Value for filter key
            type: string
            example: Science
          addsubcategories:
            description: Return subcategories info (1 = yes, 0 = no)
            type: integer
            default: 1
    responses:
      200:
        body:
          application/json:
            type: coreCourseGetCategories
            example: !include /examples/courseCategory/getCategories-example.json

/core_course_create_categories:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course Category - Create Categories
    description: Create one or more new course categories
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle webservice token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_create_categories
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          categories[0][name]:
            description: Category name
            type: string
            required: true
          categories[0][parent]:
            description: Parent category id (0 = root)
            type: integer
            default: 0
          categories[0][idnumber]:
            description: Category idnumber (optional)
            type: string
          categories[0][description]:
            description: Category description (optional)
            type: string
          categories[0][descriptionformat]:
            description: Description format (1=HTML, 0=MOODLE, 2=PLAIN, 4=MARKDOWN)
            type: integer
            default: 1
          categories[0][theme]:
            description: Theme, optional
            type: string
    responses:
      200:
        body:
          application/json:
            type: coreCourseCreateCategories
            example: !include /examples/courseCategory/createCategories-example.json

/core_course_update_categories:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course Category - Update Categories
    description: Update one or more existing course categories
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle webservice token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_update_categories
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          categories[0][id]:
            description: Category id to update (required)
            type: integer
            required: true
            example: 5
          categories[0][name]:
            description: New category name (optional)
            type: string
            example: Updated Category Name
          categories[0][idnumber]:
            description: New category idnumber (optional)
            type: string
            example: CAT2025
          categories[0][parent]:
            description: New parent category id (optional)
            type: integer
            example: 0
          categories[0][description]:
            description: New description (optional)
            type: string
            example: Updated description here.
          categories[0][descriptionformat]:
            description: Description format (1=HTML, 0=MOODLE, 2=PLAIN, 4=MARKDOWN)
            type: integer
            default: 1
            example: 1
          categories[0][theme]:
            description: New theme name (optional)
            type: string
            example: default
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
            
/core_course_delete_categories:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Course Category - Delete Categories
    description: Delete one or more course categories
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle web service token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_course_delete_categories
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          categories[0][id]:
            description: Category id to delete (required)
            type: integer
            required: true
            example: 123
          categories[0][newparent]:
            description: Category id to move contents to (optional, cannot be root)
            type: integer
            example: 5
          categories[0][recursive]:
            description: Delete recursively flag (1 = delete all contents recursively, 0 = move contents to newparent)
            type: integer
            default: 0
            example: 0
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_get_groups:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Get Group
    description: Returns detailed information for specified groups.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle web service token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_get_groups
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          groupids[0]:
            description: Group ID to fetch details for (use multiple with incremented indices)
            type: integer
            required: true
            example: 12
    responses:
      200:
        body:
          application/json:
            type: coreGroupGetGroups
            example: !include /examples/groups/getGroups-example.json
          
/core_group_create_groups:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Create Group
    description: Creates new groups in a course.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle web service token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_create_groups
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          groups[0][courseid]:
            description: ID of the course where the group will be created
            type: integer
            required: true
            example: 101
          groups[0][name]:
            description: Multilang compatible group name unique within course
            type: string
            required: true
            example: Example Group Name
          groups[0][description]:
            description: Group description text
            type: string
            required: true
            example: Description for the group
          groups[0][descriptionformat]:
            description: Description format (1=HTML, 0=MOODLE, 2=PLAIN, 4=MARKDOWN)
            type: integer
            default: 1
            example: 1
          groups[0][enrolmentkey]:
            description: Optional group enrol secret phrase
            type: string
            required: false
            example: secret123
          groups[0][idnumber]:
            description: Optional ID number for the group
            type: string
            required: false
            example: GRP001
          groups[0][visibility]:
            description: Group visibility mode (0=Visible to all, 1=Visible to members, 2=See own membership, 3=Membership hidden)
            type: integer
            default: 0
            example: 0
          groups[0][participation]:
            description: Activity participation enabled? Only for “all” and “members” visibility, default true
            type: integer
            default: 1
            example: 1
          groups[0][customfields][0][shortname]:
            description: Custom field shortname (optional)
            type: string
            required: false
            example: customfield1
          groups[0][customfields][0][value]:
            description: Custom field value (optional)
            type: string
            required: false
            example: customvalue1
    responses:
      200:
        body:
          application/json:
            type: coreGroupCreateGroups
            example: !include /examples/groups/createGroups-example.json

/core_group_update_groups:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Update Group
    description: Update one or more existing groups
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            description: Moodle web service token
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            type: string
            required: true
            description: Moodle function name
            example: core_group_update_groups
          moodlewsrestformat:
            type: string
            required: true
            description: Response format (json/xml)
            example: json
          groups[0][id]:
            type: integer
            required: true
            description: ID of the group to update
            example: 12
          groups[0][name]:
            type: string
            required: true
            description: Multilang compatible group name
            example: Updated Group Name
          groups[0][description]:
            type: string
            required: false
            description: Group description text
            example: Updated description
          groups[0][descriptionformat]:
            type: integer
            required: false
            default: 1
            description: Description format (1=HTML, 0=MOODLE, 2=PLAIN, 4=MARKDOWN)
            example: 1
          groups[0][enrolmentkey]:
            type: string
            required: false
            description: Group enrol secret phrase
            example: newsecret
          groups[0][idnumber]:
            type: string
            required: false
            description: Group id number
            example: GRP001
          groups[0][visibility]:
            type: string
            required: false
            description: Group visibility mode (0=all,1=members,2=own membership,3=hidden)
            example: "0"
          groups[0][participation]:
            type: integer
            required: false
            description: Activity participation enabled? Only for “all” and “members” visibility
            example: 1
          groups[0][customfields][0][shortname]:
            type: string
            required: false
            description: Custom field shortname
            example: customfield1
          groups[0][customfields][0][value]:
            type: string
            required: false
            description: Custom field value
            example: customvalue1
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
           
/core_group_delete_groups:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Delete Group
    description: Delete one or more specified groups.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            description: Moodle web service token
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            type: string
            required: true
            description: Moodle function name
            example: core_group_delete_groups
          moodlewsrestformat:
            type: string
            required: true
            description: Response format (json/xml)
            example: json
          groupids[0]:
            type: integer
            required: true
            description: Group ID to delete (use incremented index for multiple)
            example: 123
          groupids[1]:
            type: integer
            description: Additional Group ID to delete (optional)
            example: 456
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/core_group_get_course_groups:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Get Course Groups
    description: Returns all groups in the specified course
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle web service token
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_get_course_groups
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courseid:
            description: ID of course to fetch groups for
            type: integer
            required: true
            example: 101
    responses:
      200:
        body:
          application/json:
            type: coreGroupGetCourseGroups
            example: !include /examples/groups/getCourseGroups-example.json
/core_group_get_course_groupings:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Get Groupings
    description: Returns all groupings in the specified course.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle web service token
            type: string
            required: true
            example: abcdef1234567890abcdef1234567890
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_get_course_groupings
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          courseid:
            description: ID of course to fetch groupings for
            type: integer
            required: true
            example: 101
    responses:
      200:
        body:
          application/json:
            type: coreGroupGetCourseGroupings
            example: !include /examples/groups/getCourseGroupings-example.json
/core_group_update_groupings:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Groups - Update Groupings
    description: Updates existing groupings
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Moodle web service token
            type: string
            required: true
            example: abcdef1234567890abcdef1234567890
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: core_group_update_groupings
          moodlewsrestformat:
            description: Response format (json or xml)
            type: string
            required: true
            example: json
          groupings[0][id]:
            description: ID of the grouping to update
            type: integer
            required: true
            example: 42
          groupings[0][name]:
            description: Multilang compatible grouping name, course unique
            type: string
            required: true
            example: Updated Grouping Name
          groupings[0][description]:
            description: Grouping description text
            type: string
            required: true
            example: Updated description text
          groupings[0][descriptionformat]:
            description: Description format (1=HTML, 0=MOODLE, 2=PLAIN, 4=MARKDOWN)
            type: integer
            default: 1
            example: 1
          groupings[0][idnumber]:
            description: Optional grouping id number
            type: string
            example: GRPUPD1
          groupings[0][customfields][0][shortname]:
            description: Custom field shortname (optional)
            type: string
            example: customfield1
          groupings[0][customfields][0][value]:
            description: Custom field value (optional)
            type: string
            example: customvalue1
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json
/enrol_manual_enrol_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Enrollment - Enroll Users
    description: Enrol users into a course in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token
            type: string
            required: true
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: enrol_manual_enrol_users
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          enrolments[0][roleid]:
            description: Role to assign 
            type: integer
            required: true
            example: 5
          enrolments[0][userid]:
            description: User ID to enrol
            type: integer
            required: true
            example: 15
          enrolments[0][courseid]:
            description: Course ID to enrol user in
            type: integer
            required: true
            example: 8
          enrolments[0][timestart]?:
            description: Optional enrolment start timestamp
            type: integer
            example: 1689264000
          enrolments[0][timeend]?:
            description: Optional enrolment end timestamp
            type: integer
            example: 1691865600
          enrolments[0][suspend]?:
            description: Suspend status 
            type: integer
            example: 0
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json

/enrol_manual_unenrol_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Enrollment - Unenroll Users
    description: Unenrol users from a course in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            description: Token
            type: string
            required: true
          wsfunction:
            description: Moodle function name
            type: string
            required: true
            example: enrol_manual_unenrol_users
          moodlewsrestformat:
            description: Response format
            type: string
            required: true
            example: json
          enrolments[0][userid]:
            description: User ID to unenrol
            type: integer
            required: true
            example: 15
          enrolments[0][courseid]:
            description: Course ID to unenrol from
            type: integer
            required: true
            example: 8
          enrolments[0][roleid]?:
            description: Optional role ID
            type: integer
            example: 5
    responses:
      200:
        body:
          application/json:
            type: commonResponse
            example: !include /examples/common/common-example.json

/core_enrol_get_enrolled_users:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Enrollment - Get Enrolled Users
    description: Retrieve a list of users enrolled in a specific course.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            type: string
            required: true
            example: core_enrol_get_enrolled_users
          moodlewsrestformat:
            type: string
            required: true
            example: json
          courseid:
            description: Course ID to fetch enrolled users from
            type: integer
            required: true
            example: 8
          options[0][name]?:
            description: Optional filter option name (e.g. withcapability, groupid, onlyactive, etc.)
            type: string
            example: withcapability
          options[0][value]?:
            description: Value for the option
            type: string
            example: moodle/course:update
    responses:
      200:
        body:
          application/json:
            type: coreEnrolGetEnrolledUsers
            example: !include /examples/enrollment/getEnrolledUsers-example.json

/core_enrol_get_users_courses:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Enrollment - Get User's Courses
    description: Retrieve a list of courses a specific user is enrolled in.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            type: string
            required: true
            example: core_enrol_get_users_courses
          moodlewsrestformat:
            type: string
            required: true
            example: json
          userid:
            description: User ID
            type: integer
            required: true
            example: 25
          returnusercount?:
            description: Whether to include count of enrolled users for each course (1 = yes, 0 = no). Default is 1.
            type: integer
            example: 0
    responses:
      200:
        body:
          application/json:
            type: coreEnrolGetUsersCoursesResponse
            example: !include /examples/enrollment/getUsersCourses-example.json


/core_enrol_unenrol_user_enrolment:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Enrollment - Unenroll Users
    description: Unenrol a user from a course using their enrolment ID in Moodle.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            description: Authentication token
            example: db6ccaf6e69123c284e4a5710be8b875
          wsfunction:
            type: string
            required: true
            description: Moodle function name
            example: core_enrol_unenrol_user_enrolment
          moodlewsrestformat:
            type: string
            required: true
            description: Response format
            example: json
          ueid:
            type: integer
            required: true
            description: User enrolment ID
            example: 123
    responses:
      200:
        body:
          application/json:
            type: coreEnrolUnenrolUserEnrolment
            example: !include /examples/enrollment/unenrolUserEnrolment-example.json

/core_cohort_create_cohorts:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Create Cohorts
    description: Creates one or more cohorts in Moodle
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
          wsfunction:
            type: string
            enum: [ core_cohort_create_cohorts ]
            required: true
          moodlewsrestformat:
            type: string
            enum: [ json ]
            required: true
          cohorts[0][categorytype][type]:
            type: string
            required: true
            example: system
          cohorts[0][categorytype][value]:
            type: string
            required: true
            example: "0"
          cohorts[0][name]:
            type: string
            required: true
            example: IT Cohort 123
          cohorts[0][idnumber]:
            type: string
            required: true
            example: ITC123
          cohorts[0][description]?:
            type: string
            example: This is a test cohort
          cohorts[0][descriptionformat]?:
            type: string   # must be string because x-www-form-urlencoded encodes numbers as strings
            example: "1"
          cohorts[0][visible]?:
            type: string   # keep string here, not integer
            example: "1"
          cohorts[0][theme]?:
            type: string
            example: boost
    responses:
      200:
        body:
          application/json:
            type: Cohort[]
            example: !include /examples/cohort/createCohorts-example.json

/core_cohort_add_cohort_members:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Add Cohort Members
    description: Adds one or more users to a cohort.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: "yourtokenhere"
          wsfunction:
            type: string
            required: true
            example: core_cohort_add_cohort_members
          moodlewsrestformat:
            type: string
            required: true
            example: json
          members[0][cohorttype][type]:
            type: string
            example: id
          members[0][cohorttype][value]:
            type: string
            example: "3"
          members[0][usertype][type]:
            type: string
            example: id
          members[0][usertype][value]:
            type: string
            example: "15"
    responses:
      200:
        body:
          application/json:
            type: AddCohortMemberResponse
            example: !include /examples/cohort/addCohortMembers-example.json

/core_cohort_delete_cohorts:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Delete Cohort
    description: Deletes one or more cohorts.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: "yourtokenhere"
          wsfunction:
            type: string
            required: true
            example: core_cohort_delete_cohorts
          moodlewsrestformat:
            type: string
            required: true
            example: json
          cohortids[0]:
            type: integer
            required: true
            example: 3
    responses:
      200:
        description: Successful deletion response
        body:
          application/json:
            type: DeleteCohortResponse
            example: !include /examples/cohort/deleteCohorts-example.json   

/core_cohort_delete_cohort_members:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Delete Cohort Member
    description: Deletes one or more users from a cohort.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: "yourtokenhere"
          wsfunction:
            type: string
            required: true
            example: core_cohort_delete_cohort_members
          moodlewsrestformat:
            type: string
            required: true
            example: json
          members[0][cohortid]:
            type: integer
            required: true
            example: 3
          members[0][userid]:
            type: integer
            required: true
            example: 15
    responses:
      200:
        description: Successful deletion response
        body:
          application/json:
            type: DeleteCohortMemberResponse
            example: !include /examples/cohort/deleteCohortMembers-example.json

/core_cohort_get_cohort_members:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Get Cohort Members
    description: Returns the list of users in one or more cohorts.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: "yourtokenhere"
          wsfunction:
            type: string
            required: true
            example: core_cohort_get_cohort_members
          moodlewsrestformat:
            type: string
            required: true
            example: json
          cohortids[0]:
            type: integer
            required: true
            example: 3
    responses:
      200:
        description: Successful response with cohort members
        body:
          application/json:
            type: GetCohortMembers
            example: !include /examples/cohort/getCohortMembers-example.json

/core_cohort_get_cohorts:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Get Cohorts
    description: Returns details of one or more cohorts. If no IDs are passed, all cohorts will be returned.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
            example: "yourtokenhere"
          wsfunction:
            type: string
            required: true
            example: core_cohort_get_cohorts
          moodlewsrestformat:
            type: string
            required: true
            example: json
          cohortids[0]?:
            type: integer
            example: 3
    responses:
      200:
        description: Successful response with cohort details
        body:
          application/json:
            type: CohortItem[]
            example: !include /examples/cohort/getCohorts-example.json
/core_cohort_update_cohorts:
  post:
    is: [commonHeaders,errorResponse]
    displayName: Cohort - Update Cohorts
    description: Updates one or more cohorts in Moodle.
    body:
      application/x-www-form-urlencoded:
        properties:
          wstoken:
            type: string
            required: true
          wsfunction:
            type: string
            enum: [ core_cohort_update_cohorts ]
            required: true
          moodlewsrestformat:
            type: string
            enum: [ json ]
            required: true
          cohorts[0][id]:
            type: integer
            example: 3
          cohorts[0][categorytype][type]:
            type: string
            example: system
          cohorts[0][categorytype][value]:
            type: string
            example: "0"
          cohorts[0][name]:
            type: string
            example: Updated IT Cohort
          cohorts[0][idnumber]:
            type: string
            example: ITC001
          cohorts[0][description]?:
            type: string
            example: Updated cohort description
          cohorts[0][descriptionformat]?:
            type: integer
            example: 1
          cohorts[0][visible]?:
            type: integer
            example: 1
          cohorts[0][theme]?:
            type: string
            example: boost
          cohorts[0][customfields][0][shortname]?:
            type: string
            example: department
          cohorts[0][customfields][0][value]?:
            type: string
            example: IT
    responses:
      200:
        body:
          application/json:
            type: CohortTypes   
            example: !include /examples/cohort/updateCohorts-example.json